import Head from 'next/head';
import Image from 'next/image';
import Banner from '../components/banner/banner';
import Card from '../components/card/card';
import NavBar from '../components/nav/navbar';
import styles from '../styles/Home.module.css';
import SectionCards from '../components/card/section-cards';

export default function Home() {
  const disneyVideos = [
    {
      imgUrl:"/static/clifford.webp"
    },
    {
      imgUrl:"/static/clifford.webp"
    },
    {
      imgUrl:"/static/clifford.webp"
    },
    {
      imgUrl:"/static/clifford.webp"
    },
  ]
  return (
    <div className={styles.container}>
      <Head>
        <title>KronosFlix</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <NavBar username='Kronos@gmail.com' />
      <Banner
        title='Clifford the green dog'
        subTitle='a cute dog'
        imgUrl='/static/clifford.webp'
      />

      <div className={styles.sectionWrapper}>
        <SectionCards title='disney' videos={disneyVideos} size='large'/>
        <SectionCards title='disney' videos={disneyVideos} size='medium' />
      </div>
    </div>
  );
}
